name: Build and Publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build, test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sanderdona/arm-test
          registry: docker.io
          addLatest: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}